### ISSUE TITLE
2x BookMonkey API

### ISSUE THREAD

**Issue by JohannesHoppe** [workshops-de/bookmonkey-api#2]
Wir haben wohl zwei Mal das selbe entwickelt.
Ihr könnt gerne die gehostete API in euren Workshops verwenden, wenn ihr mögt:

http://book-monkey2-api.angular2buch.de/
https://github.com/Angular2Buch/book-monkey2-api

**Comment by ghost** [comment]
Hallo Johannes, danke, aber wir haben auch selbst seit 2 Jahren eine gehostete Version.
